version: "3"
services:
    rabbitmq:
        environment:
            - "RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQQ"
            - "RABBITMQ_DEFAULT_USER=appuser"
            - "RABBITMQ_DEFAULT_PASS=@ecneoe#022"
            - "RABBITMQ_DEFAULT_VHOST=/"
        ports:
            - "15672:15672"
            - "5672:5672"
        image: "rabbitmq:3.6-management-alpine"               
        restart: always
        hostname: local
        volumes:
            - rabbit-data:/var/lib/rabbitmq
        networks:
            - dev_backend

networks:
    dev_backend:
        external: true

volumes:
    rabbit-data: