version: "3"
services:
    postgres:
        image: postgres:13-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: postgrespassword
            POSTGRES_USER: postgresuser
            POSTGRES_DB: app
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - dev_backend
networks:
    dev_backend:
        external: true
volumes:
    postgres-data: