version: "3"
services:
    postgres:
        image: postgres:10-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: kwoat-svc
            POSTGRES_USER: quote_svc
            POSTGRES_DB: quote
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data: