version: "3.9"
services:
    postgres:
        image: postgres:13-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: kwoat-svc
            POSTGRES_USER: quote_svc
            POSTGRES_DB: quote
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - dev_backend
networks:
    dev_backend:
        external: true
volumes:
    postgres-data: