version: "3"
services:
    postgres:
        container_name: postgresdb
        image: postgres:15-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: postgrespassword
            POSTGRES_USER: postgresuser
            POSTGRES_DB: app
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - dev_backend
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: postgrespassword
        ports:
            - "5050:80"
        networks:
            - dev_backend
networks:
    dev_backend:
        external: true
volumes:
    postgres-data: