version: "3"
services:
    redis:
        image: "redis:6.0.9-alpine"
        command: redis-server --requirepass Cdk-0101 --appendonly yes
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
volumes:
    redis-data:        