version: "3"
services:
    redis:
        image: "redis:6.0.9-alpine"
        command: redis-server --requirepass app-2101 --appendonly yes
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        networks:
            - dev_backend

networks:
    dev_backend:
        external: true
        
volumes:
    redis-data:        